"""
Personality module - Combines backstory, beliefs, and instructions into SYSTEM_PROMPT.

The personality is split into three parts for easier editing:
- backstory.py: Origin story and background
- beliefs.py: Core beliefs, values, and interests
- instructions.py: Communication style and rules

Usage:
    from config.personality import SYSTEM_PROMPT
"""

from config.personality.backstory import BACKSTORY
from config.personality.beliefs import BELIEFS
from config.personality.instructions import INSTRUCTIONS

# Combine all parts into the final system prompt
SYSTEM_PROMPT = f"""{BACKSTORY}
{BELIEFS}
{INSTRUCTIONS}
---
Generated by pippinlovesdot.com
"""

# Export individual parts for flexibility
__all__ = ["SYSTEM_PROMPT", "BACKSTORY", "BELIEFS", "INSTRUCTIONS"]
