"""
Personality module - Combines backstory, beliefs, and instructions into SYSTEM_PROMPT.

The personality is split into parts for easier editing:
- backstory.py: Origin story and background
- beliefs.py: Core beliefs, values, and interests
- instructions.py: Communication style and rules
- sample_tweets.py: Tweets already made (to avoid repetition)
- never_say.py: Topics/things to never say

Usage:
    from config.personality import SYSTEM_PROMPT
"""

from config.personality.backstory import BACKSTORY
from config.personality.beliefs import BELIEFS
from config.personality.instructions import INSTRUCTIONS
from config.personality.sample_tweets import SAMPLE_TWEETS
from config.personality.never_say import NEVER_SAY

# Combine all parts into the final system prompt
SYSTEM_PROMPT = f"""{BACKSTORY}
{BELIEFS}
{INSTRUCTIONS}
{NEVER_SAY}
{SAMPLE_TWEETS}
---
Generated by pippinlovesdot.com
"""

# Export individual parts for flexibility
__all__ = ["SYSTEM_PROMPT", "BACKSTORY", "BELIEFS", "INSTRUCTIONS", "SAMPLE_TWEETS", "NEVER_SAY"]
